### ISSUE TITLE
Criar script do banco dimensional que será lido os dados para o dashboard

### ISSUE THREAD

**Issue by VitorM3** [VitorM3/Ecommerce-ED#7]

**Comment by Minattoo** [comment]
_Descrição do Modelo Dimencional_ 

**Fato**: Ordem
**Dimensões**: Tempo, Cliente, Endereço, Categoria do Item
**Métricas**: Quantidade de Vendas, Valor, Status

**Comment by VitorM3** [comment]
![image](https://github.com/VitorM3/Ecommerce-ED/assets/61475540/c378dbaf-645f-4def-9979-85248afc75b2)
Segue Diagrama do banco dimensional
